#!/usr/bin/env bun
// Codegen for the embedded web bundle.
//
// Walks `web/dist/`, emits `server/src/web/assets.ts` with one
// `import … with { type: "file" }` line per file and an ASSETS map
// keyed by forward-slash relative path. When the result is fed to
// `bun build --compile`, every imported file gets bundled into the
// resulting binary.
//
// Run from repo root:
//     bun --cwd web run build
//     bun scripts/gen-web-assets.ts
//     bun build --compile --target=bun-darwin-arm64 \
//        --outfile=dist/brain server/src/index.ts

import { readdirSync, statSync, writeFileSync } from "node:fs";
import { join, relative, sep } from "node:path";

const REPO_ROOT = new URL("..", import.meta.url).pathname;
const DIST = join(REPO_ROOT, "web", "dist");
const OUT = join(REPO_ROOT, "server", "src", "web", "assets.ts");

function walk(dir: string, acc: string[] = []): string[] {
  for (const name of readdirSync(dir)) {
    const abs = join(dir, name);
    const s = statSync(abs);
    if (s.isDirectory()) walk(abs, acc);
    else if (s.isFile()) acc.push(abs);
  }
  return acc;
}

if (!statSync(DIST, { throwIfNoEntry: false })?.isDirectory()) {
  console.error(
    `[gen-web-assets] ${DIST} does not exist. Run \`bun --cwd web run build\` first.`,
  );
  process.exit(1);
}

const files = walk(DIST).sort();
if (files.length === 0) {
  console.error(`[gen-web-assets] ${DIST} is empty`);
  process.exit(1);
}

// Build per-file import alias + the ASSETS map.
const imports: string[] = [];
const entries: string[] = [];
files.forEach((abs, i) => {
  const rel = relative(DIST, abs).split(sep).join("/");
  // Path used in the import statement, relative to assets.ts (which lives
  // in server/src/web/). web/dist sits at repo-root/web/dist, assets.ts
  // sits at repo-root/server/src/web → up three: ../../../web/dist/<rel>.
  const importPath = "../../../web/dist/" + rel;
  const alias = "f" + i;
  imports.push(
    `import ${alias} from ${JSON.stringify(importPath)} with { type: "file" };`,
  );
  entries.push(`  ${JSON.stringify(rel)}: ${alias},`);
});

const body = `// @ts-nocheck
// ------------------------------------------------------------------
// AUTO-GENERATED by scripts/gen-web-assets.ts — do not edit by hand.
// Regenerate after every \`bun --cwd web run build\`.
//
// @ts-nocheck because the \`with { type: "file" }\` import attribute is
// a Bun-bundler convention (returns a string handle resolvable via
// Bun.file()), not a standard TypeScript-recognised module shape.
// ------------------------------------------------------------------

${imports.join("\n")}

export const ASSETS: Record<string, string> = {
${entries.join("\n")}
};

export const ASSETS_GENERATED_AT: number | null = ${Date.now()};
`;

writeFileSync(OUT, body);
console.log(
  `[gen-web-assets] wrote ${OUT} — ${files.length} files embedded ` +
    `(${(files.reduce((n, f) => n + statSync(f).size, 0) / 1024).toFixed(1)} KiB)`,
);
