// @ts-nocheck
// ------------------------------------------------------------------
// AUTO-GENERATED by scripts/gen-web-assets.ts — do not edit by hand.
// Regenerate after every `bun --cwd web run build`.
//
// @ts-nocheck because the `with { type: "file" }` import attribute is
// a Bun-bundler convention (returns a string handle resolvable via
// Bun.file()), not a standard TypeScript-recognised module shape.
// ------------------------------------------------------------------

import f0 from "../../../web/dist/.DS_Store" with { type: "file" };
import f1 from "../../../web/dist/assets/KaTeX_AMS-Regular-BQhdFMY1.woff2" with { type: "file" };
import f2 from "../../../web/dist/assets/KaTeX_AMS-Regular-DMm9YOAa.woff" with { type: "file" };
import f3 from "../../../web/dist/assets/KaTeX_AMS-Regular-DRggAlZN.ttf" with { type: "file" };
import f4 from "../../../web/dist/assets/KaTeX_Caligraphic-Bold-ATXxdsX0.ttf" with { type: "file" };
import f5 from "../../../web/dist/assets/KaTeX_Caligraphic-Bold-BEiXGLvX.woff" with { type: "file" };
import f6 from "../../../web/dist/assets/KaTeX_Caligraphic-Bold-Dq_IR9rO.woff2" with { type: "file" };
import f7 from "../../../web/dist/assets/KaTeX_Caligraphic-Regular-CTRA-rTL.woff" with { type: "file" };
import f8 from "../../../web/dist/assets/KaTeX_Caligraphic-Regular-Di6jR-x-.woff2" with { type: "file" };
import f9 from "../../../web/dist/assets/KaTeX_Caligraphic-Regular-wX97UBjC.ttf" with { type: "file" };
import f10 from "../../../web/dist/assets/KaTeX_Fraktur-Bold-BdnERNNW.ttf" with { type: "file" };
import f11 from "../../../web/dist/assets/KaTeX_Fraktur-Bold-BsDP51OF.woff" with { type: "file" };
import f12 from "../../../web/dist/assets/KaTeX_Fraktur-Bold-CL6g_b3V.woff2" with { type: "file" };
import f13 from "../../../web/dist/assets/KaTeX_Fraktur-Regular-CB_wures.ttf" with { type: "file" };
import f14 from "../../../web/dist/assets/KaTeX_Fraktur-Regular-CTYiF6lA.woff2" with { type: "file" };
import f15 from "../../../web/dist/assets/KaTeX_Fraktur-Regular-Dxdc4cR9.woff" with { type: "file" };
import f16 from "../../../web/dist/assets/KaTeX_Main-Bold-Cx986IdX.woff2" with { type: "file" };
import f17 from "../../../web/dist/assets/KaTeX_Main-Bold-Jm3AIy58.woff" with { type: "file" };
import f18 from "../../../web/dist/assets/KaTeX_Main-Bold-waoOVXN0.ttf" with { type: "file" };
import f19 from "../../../web/dist/assets/KaTeX_Main-BoldItalic-DxDJ3AOS.woff2" with { type: "file" };
import f20 from "../../../web/dist/assets/KaTeX_Main-BoldItalic-DzxPMmG6.ttf" with { type: "file" };
import f21 from "../../../web/dist/assets/KaTeX_Main-BoldItalic-SpSLRI95.woff" with { type: "file" };
import f22 from "../../../web/dist/assets/KaTeX_Main-Italic-3WenGoN9.ttf" with { type: "file" };
import f23 from "../../../web/dist/assets/KaTeX_Main-Italic-BMLOBm91.woff" with { type: "file" };
import f24 from "../../../web/dist/assets/KaTeX_Main-Italic-NWA7e6Wa.woff2" with { type: "file" };
import f25 from "../../../web/dist/assets/KaTeX_Main-Regular-B22Nviop.woff2" with { type: "file" };
import f26 from "../../../web/dist/assets/KaTeX_Main-Regular-Dr94JaBh.woff" with { type: "file" };
import f27 from "../../../web/dist/assets/KaTeX_Main-Regular-ypZvNtVU.ttf" with { type: "file" };
import f28 from "../../../web/dist/assets/KaTeX_Math-BoldItalic-B3XSjfu4.ttf" with { type: "file" };
import f29 from "../../../web/dist/assets/KaTeX_Math-BoldItalic-CZnvNsCZ.woff2" with { type: "file" };
import f30 from "../../../web/dist/assets/KaTeX_Math-BoldItalic-iY-2wyZ7.woff" with { type: "file" };
import f31 from "../../../web/dist/assets/KaTeX_Math-Italic-DA0__PXp.woff" with { type: "file" };
import f32 from "../../../web/dist/assets/KaTeX_Math-Italic-flOr_0UB.ttf" with { type: "file" };
import f33 from "../../../web/dist/assets/KaTeX_Math-Italic-t53AETM-.woff2" with { type: "file" };
import f34 from "../../../web/dist/assets/KaTeX_SansSerif-Bold-CFMepnvq.ttf" with { type: "file" };
import f35 from "../../../web/dist/assets/KaTeX_SansSerif-Bold-D1sUS0GD.woff2" with { type: "file" };
import f36 from "../../../web/dist/assets/KaTeX_SansSerif-Bold-DbIhKOiC.woff" with { type: "file" };
import f37 from "../../../web/dist/assets/KaTeX_SansSerif-Italic-C3H0VqGB.woff2" with { type: "file" };
import f38 from "../../../web/dist/assets/KaTeX_SansSerif-Italic-DN2j7dab.woff" with { type: "file" };
import f39 from "../../../web/dist/assets/KaTeX_SansSerif-Italic-YYjJ1zSn.ttf" with { type: "file" };
import f40 from "../../../web/dist/assets/KaTeX_SansSerif-Regular-BNo7hRIc.ttf" with { type: "file" };
import f41 from "../../../web/dist/assets/KaTeX_SansSerif-Regular-CS6fqUqJ.woff" with { type: "file" };
import f42 from "../../../web/dist/assets/KaTeX_SansSerif-Regular-DDBCnlJ7.woff2" with { type: "file" };
import f43 from "../../../web/dist/assets/KaTeX_Script-Regular-C5JkGWo-.ttf" with { type: "file" };
import f44 from "../../../web/dist/assets/KaTeX_Script-Regular-D3wIWfF6.woff2" with { type: "file" };
import f45 from "../../../web/dist/assets/KaTeX_Script-Regular-D5yQViql.woff" with { type: "file" };
import f46 from "../../../web/dist/assets/KaTeX_Size1-Regular-C195tn64.woff" with { type: "file" };
import f47 from "../../../web/dist/assets/KaTeX_Size1-Regular-Dbsnue_I.ttf" with { type: "file" };
import f48 from "../../../web/dist/assets/KaTeX_Size1-Regular-mCD8mA8B.woff2" with { type: "file" };
import f49 from "../../../web/dist/assets/KaTeX_Size2-Regular-B7gKUWhC.ttf" with { type: "file" };
import f50 from "../../../web/dist/assets/KaTeX_Size2-Regular-Dy4dx90m.woff2" with { type: "file" };
import f51 from "../../../web/dist/assets/KaTeX_Size2-Regular-oD1tc_U0.woff" with { type: "file" };
import f52 from "../../../web/dist/assets/KaTeX_Size3-Regular-CTq5MqoE.woff" with { type: "file" };
import f53 from "../../../web/dist/assets/KaTeX_Size3-Regular-DgpXs0kz.ttf" with { type: "file" };
import f54 from "../../../web/dist/assets/KaTeX_Size4-Regular-BF-4gkZK.woff" with { type: "file" };
import f55 from "../../../web/dist/assets/KaTeX_Size4-Regular-DWFBv043.ttf" with { type: "file" };
import f56 from "../../../web/dist/assets/KaTeX_Size4-Regular-Dl5lxZxV.woff2" with { type: "file" };
import f57 from "../../../web/dist/assets/KaTeX_Typewriter-Regular-C0xS9mPB.woff" with { type: "file" };
import f58 from "../../../web/dist/assets/KaTeX_Typewriter-Regular-CO6r4hn1.woff2" with { type: "file" };
import f59 from "../../../web/dist/assets/KaTeX_Typewriter-Regular-D3Ib7_Hf.ttf" with { type: "file" };
import f60 from "../../../web/dist/assets/arc-CVzW8rIw.js" with { type: "file" };
import f61 from "../../../web/dist/assets/arc-CVzW8rIw.js.map" with { type: "file" };
import f62 from "../../../web/dist/assets/architectureDiagram-3BPJPVTR-B8DxxJjO.js" with { type: "file" };
import f63 from "../../../web/dist/assets/architectureDiagram-3BPJPVTR-B8DxxJjO.js.map" with { type: "file" };
import f64 from "../../../web/dist/assets/blockDiagram-GPEHLZMM-Cwi8yMgg.js" with { type: "file" };
import f65 from "../../../web/dist/assets/blockDiagram-GPEHLZMM-Cwi8yMgg.js.map" with { type: "file" };
import f66 from "../../../web/dist/assets/c4Diagram-AAUBKEIU-oBCovhPE.js" with { type: "file" };
import f67 from "../../../web/dist/assets/c4Diagram-AAUBKEIU-oBCovhPE.js.map" with { type: "file" };
import f68 from "../../../web/dist/assets/channel-_zKLHA6o.js" with { type: "file" };
import f69 from "../../../web/dist/assets/channel-_zKLHA6o.js.map" with { type: "file" };
import f70 from "../../../web/dist/assets/chunk-2J33WTMH-Bm2V3Iv1.js" with { type: "file" };
import f71 from "../../../web/dist/assets/chunk-2J33WTMH-Bm2V3Iv1.js.map" with { type: "file" };
import f72 from "../../../web/dist/assets/chunk-4BX2VUAB-Cyp1xMGZ.js" with { type: "file" };
import f73 from "../../../web/dist/assets/chunk-4BX2VUAB-Cyp1xMGZ.js.map" with { type: "file" };
import f74 from "../../../web/dist/assets/chunk-55IACEB6-Dhe_8U6Q.js" with { type: "file" };
import f75 from "../../../web/dist/assets/chunk-55IACEB6-Dhe_8U6Q.js.map" with { type: "file" };
import f76 from "../../../web/dist/assets/chunk-727SXJPM-C3Feq6dm.js" with { type: "file" };
import f77 from "../../../web/dist/assets/chunk-727SXJPM-C3Feq6dm.js.map" with { type: "file" };
import f78 from "../../../web/dist/assets/chunk-AQP2D5EJ-DhgwVsdI.js" with { type: "file" };
import f79 from "../../../web/dist/assets/chunk-AQP2D5EJ-DhgwVsdI.js.map" with { type: "file" };
import f80 from "../../../web/dist/assets/chunk-FMBD7UC4-e6vAsuuH.js" with { type: "file" };
import f81 from "../../../web/dist/assets/chunk-FMBD7UC4-e6vAsuuH.js.map" with { type: "file" };
import f82 from "../../../web/dist/assets/chunk-ND2GUHAM-FwQ3Wrck.js" with { type: "file" };
import f83 from "../../../web/dist/assets/chunk-ND2GUHAM-FwQ3Wrck.js.map" with { type: "file" };
import f84 from "../../../web/dist/assets/chunk-QZHKN3VN-DTGpMUZK.js" with { type: "file" };
import f85 from "../../../web/dist/assets/chunk-QZHKN3VN-DTGpMUZK.js.map" with { type: "file" };
import f86 from "../../../web/dist/assets/classDiagram-4FO5ZUOK-C1xAtkQI.js" with { type: "file" };
import f87 from "../../../web/dist/assets/classDiagram-4FO5ZUOK-C1xAtkQI.js.map" with { type: "file" };
import f88 from "../../../web/dist/assets/classDiagram-v2-Q7XG4LA2-C1xAtkQI.js" with { type: "file" };
import f89 from "../../../web/dist/assets/classDiagram-v2-Q7XG4LA2-C1xAtkQI.js.map" with { type: "file" };
import f90 from "../../../web/dist/assets/cose-bilkent-S5V4N54A-Da33WB1y.js" with { type: "file" };
import f91 from "../../../web/dist/assets/cose-bilkent-S5V4N54A-Da33WB1y.js.map" with { type: "file" };
import f92 from "../../../web/dist/assets/cytoscape.esm-BHYC38rz.js" with { type: "file" };
import f93 from "../../../web/dist/assets/cytoscape.esm-BHYC38rz.js.map" with { type: "file" };
import f94 from "../../../web/dist/assets/dagre-BM42HDAG-DkIrl7LI.js" with { type: "file" };
import f95 from "../../../web/dist/assets/dagre-BM42HDAG-DkIrl7LI.js.map" with { type: "file" };
import f96 from "../../../web/dist/assets/defaultLocale-CrowFXzY.js" with { type: "file" };
import f97 from "../../../web/dist/assets/defaultLocale-CrowFXzY.js.map" with { type: "file" };
import f98 from "../../../web/dist/assets/diagram-2AECGRRQ-CWoEKL_V.js" with { type: "file" };
import f99 from "../../../web/dist/assets/diagram-2AECGRRQ-CWoEKL_V.js.map" with { type: "file" };
import f100 from "../../../web/dist/assets/diagram-5GNKFQAL-C9Z9Bwq0.js" with { type: "file" };
import f101 from "../../../web/dist/assets/diagram-5GNKFQAL-C9Z9Bwq0.js.map" with { type: "file" };
import f102 from "../../../web/dist/assets/diagram-KO2AKTUF-Du2EWJ5m.js" with { type: "file" };
import f103 from "../../../web/dist/assets/diagram-KO2AKTUF-Du2EWJ5m.js.map" with { type: "file" };
import f104 from "../../../web/dist/assets/diagram-LMA3HP47-GGH_yPsZ.js" with { type: "file" };
import f105 from "../../../web/dist/assets/diagram-LMA3HP47-GGH_yPsZ.js.map" with { type: "file" };
import f106 from "../../../web/dist/assets/diagram-OG6HWLK6-VMYDeT1M.js" with { type: "file" };
import f107 from "../../../web/dist/assets/diagram-OG6HWLK6-VMYDeT1M.js.map" with { type: "file" };
import f108 from "../../../web/dist/assets/erDiagram-TEJ5UH35-BEqbMcJY.js" with { type: "file" };
import f109 from "../../../web/dist/assets/erDiagram-TEJ5UH35-BEqbMcJY.js.map" with { type: "file" };
import f110 from "../../../web/dist/assets/flowDiagram-I6XJVG4X-x2-Ub5G7.js" with { type: "file" };
import f111 from "../../../web/dist/assets/flowDiagram-I6XJVG4X-x2-Ub5G7.js.map" with { type: "file" };
import f112 from "../../../web/dist/assets/ganttDiagram-6RSMTGT7-DUcZWSH4.js" with { type: "file" };
import f113 from "../../../web/dist/assets/ganttDiagram-6RSMTGT7-DUcZWSH4.js.map" with { type: "file" };
import f114 from "../../../web/dist/assets/gitGraphDiagram-PVQCEYII-Cqwx4SCt.js" with { type: "file" };
import f115 from "../../../web/dist/assets/gitGraphDiagram-PVQCEYII-Cqwx4SCt.js.map" with { type: "file" };
import f116 from "../../../web/dist/assets/graph-Dqkl27Ch.js" with { type: "file" };
import f117 from "../../../web/dist/assets/graph-Dqkl27Ch.js.map" with { type: "file" };
import f118 from "../../../web/dist/assets/index-DPRjPCXf.css" with { type: "file" };
import f119 from "../../../web/dist/assets/index-WRN0oQy4.js" with { type: "file" };
import f120 from "../../../web/dist/assets/index-WRN0oQy4.js.map" with { type: "file" };
import f121 from "../../../web/dist/assets/infoDiagram-5YYISTIA-D0qbEhQe.js" with { type: "file" };
import f122 from "../../../web/dist/assets/infoDiagram-5YYISTIA-D0qbEhQe.js.map" with { type: "file" };
import f123 from "../../../web/dist/assets/init-Gi6I4Gst.js" with { type: "file" };
import f124 from "../../../web/dist/assets/init-Gi6I4Gst.js.map" with { type: "file" };
import f125 from "../../../web/dist/assets/ishikawaDiagram-YF4QCWOH-DbHmi4h_.js" with { type: "file" };
import f126 from "../../../web/dist/assets/ishikawaDiagram-YF4QCWOH-DbHmi4h_.js.map" with { type: "file" };
import f127 from "../../../web/dist/assets/journeyDiagram-JHISSGLW-Dr1IoxSi.js" with { type: "file" };
import f128 from "../../../web/dist/assets/journeyDiagram-JHISSGLW-Dr1IoxSi.js.map" with { type: "file" };
import f129 from "../../../web/dist/assets/kanban-definition-UN3LZRKU--k1I1t4r.js" with { type: "file" };
import f130 from "../../../web/dist/assets/kanban-definition-UN3LZRKU--k1I1t4r.js.map" with { type: "file" };
import f131 from "../../../web/dist/assets/layout-DO9UvE1P.js" with { type: "file" };
import f132 from "../../../web/dist/assets/layout-DO9UvE1P.js.map" with { type: "file" };
import f133 from "../../../web/dist/assets/linear-DSm5fsPb.js" with { type: "file" };
import f134 from "../../../web/dist/assets/linear-DSm5fsPb.js.map" with { type: "file" };
import f135 from "../../../web/dist/assets/mermaid.core-Ap_9pv9R.js" with { type: "file" };
import f136 from "../../../web/dist/assets/mermaid.core-Ap_9pv9R.js.map" with { type: "file" };
import f137 from "../../../web/dist/assets/mindmap-definition-RKZ34NQL-BEdV6YPh.js" with { type: "file" };
import f138 from "../../../web/dist/assets/mindmap-definition-RKZ34NQL-BEdV6YPh.js.map" with { type: "file" };
import f139 from "../../../web/dist/assets/ordinal-Cboi1Yqb.js" with { type: "file" };
import f140 from "../../../web/dist/assets/ordinal-Cboi1Yqb.js.map" with { type: "file" };
import f141 from "../../../web/dist/assets/pieDiagram-4H26LBE5-DEXyv75m.js" with { type: "file" };
import f142 from "../../../web/dist/assets/pieDiagram-4H26LBE5-DEXyv75m.js.map" with { type: "file" };
import f143 from "../../../web/dist/assets/quadrantDiagram-W4KKPZXB-D_kYuYHy.js" with { type: "file" };
import f144 from "../../../web/dist/assets/quadrantDiagram-W4KKPZXB-D_kYuYHy.js.map" with { type: "file" };
import f145 from "../../../web/dist/assets/requirementDiagram-4Y6WPE33-BKzZtHsA.js" with { type: "file" };
import f146 from "../../../web/dist/assets/requirementDiagram-4Y6WPE33-BKzZtHsA.js.map" with { type: "file" };
import f147 from "../../../web/dist/assets/sankeyDiagram-5OEKKPKP-BgQMyrSg.js" with { type: "file" };
import f148 from "../../../web/dist/assets/sankeyDiagram-5OEKKPKP-BgQMyrSg.js.map" with { type: "file" };
import f149 from "../../../web/dist/assets/sequenceDiagram-3UESZ5HK-GtB0e6xu.js" with { type: "file" };
import f150 from "../../../web/dist/assets/sequenceDiagram-3UESZ5HK-GtB0e6xu.js.map" with { type: "file" };
import f151 from "../../../web/dist/assets/stateDiagram-AJRCARHV-BFVUMSdO.js" with { type: "file" };
import f152 from "../../../web/dist/assets/stateDiagram-AJRCARHV-BFVUMSdO.js.map" with { type: "file" };
import f153 from "../../../web/dist/assets/stateDiagram-v2-BHNVJYJU-xfmCgDp0.js" with { type: "file" };
import f154 from "../../../web/dist/assets/stateDiagram-v2-BHNVJYJU-xfmCgDp0.js.map" with { type: "file" };
import f155 from "../../../web/dist/assets/timeline-definition-PNZ67QCA-D8AY6Ugr.js" with { type: "file" };
import f156 from "../../../web/dist/assets/timeline-definition-PNZ67QCA-D8AY6Ugr.js.map" with { type: "file" };
import f157 from "../../../web/dist/assets/vennDiagram-CIIHVFJN--GtxLeUW.js" with { type: "file" };
import f158 from "../../../web/dist/assets/vennDiagram-CIIHVFJN--GtxLeUW.js.map" with { type: "file" };
import f159 from "../../../web/dist/assets/wardley-L42UT6IY-DkC-hCz1.js" with { type: "file" };
import f160 from "../../../web/dist/assets/wardley-L42UT6IY-DkC-hCz1.js.map" with { type: "file" };
import f161 from "../../../web/dist/assets/wardleyDiagram-YWT4CUSO-CW3AQD05.js" with { type: "file" };
import f162 from "../../../web/dist/assets/wardleyDiagram-YWT4CUSO-CW3AQD05.js.map" with { type: "file" };
import f163 from "../../../web/dist/assets/xychartDiagram-2RQKCTM6-BNQB4-xZ.js" with { type: "file" };
import f164 from "../../../web/dist/assets/xychartDiagram-2RQKCTM6-BNQB4-xZ.js.map" with { type: "file" };
import f165 from "../../../web/dist/brainmdlogo.png" with { type: "file" };
import f166 from "../../../web/dist/icon.svg" with { type: "file" };
import f167 from "../../../web/dist/icon_.svg" with { type: "file" };
import f168 from "../../../web/dist/index.html" with { type: "file" };
import f169 from "../../../web/dist/logo.svg" with { type: "file" };
import f170 from "../../../web/dist/manifest.webmanifest" with { type: "file" };
import f171 from "../../../web/dist/sw.js" with { type: "file" };

export const ASSETS: Record<string, string> = {
  ".DS_Store": f0,
  "assets/KaTeX_AMS-Regular-BQhdFMY1.woff2": f1,
  "assets/KaTeX_AMS-Regular-DMm9YOAa.woff": f2,
  "assets/KaTeX_AMS-Regular-DRggAlZN.ttf": f3,
  "assets/KaTeX_Caligraphic-Bold-ATXxdsX0.ttf": f4,
  "assets/KaTeX_Caligraphic-Bold-BEiXGLvX.woff": f5,
  "assets/KaTeX_Caligraphic-Bold-Dq_IR9rO.woff2": f6,
  "assets/KaTeX_Caligraphic-Regular-CTRA-rTL.woff": f7,
  "assets/KaTeX_Caligraphic-Regular-Di6jR-x-.woff2": f8,
  "assets/KaTeX_Caligraphic-Regular-wX97UBjC.ttf": f9,
  "assets/KaTeX_Fraktur-Bold-BdnERNNW.ttf": f10,
  "assets/KaTeX_Fraktur-Bold-BsDP51OF.woff": f11,
  "assets/KaTeX_Fraktur-Bold-CL6g_b3V.woff2": f12,
  "assets/KaTeX_Fraktur-Regular-CB_wures.ttf": f13,
  "assets/KaTeX_Fraktur-Regular-CTYiF6lA.woff2": f14,
  "assets/KaTeX_Fraktur-Regular-Dxdc4cR9.woff": f15,
  "assets/KaTeX_Main-Bold-Cx986IdX.woff2": f16,
  "assets/KaTeX_Main-Bold-Jm3AIy58.woff": f17,
  "assets/KaTeX_Main-Bold-waoOVXN0.ttf": f18,
  "assets/KaTeX_Main-BoldItalic-DxDJ3AOS.woff2": f19,
  "assets/KaTeX_Main-BoldItalic-DzxPMmG6.ttf": f20,
  "assets/KaTeX_Main-BoldItalic-SpSLRI95.woff": f21,
  "assets/KaTeX_Main-Italic-3WenGoN9.ttf": f22,
  "assets/KaTeX_Main-Italic-BMLOBm91.woff": f23,
  "assets/KaTeX_Main-Italic-NWA7e6Wa.woff2": f24,
  "assets/KaTeX_Main-Regular-B22Nviop.woff2": f25,
  "assets/KaTeX_Main-Regular-Dr94JaBh.woff": f26,
  "assets/KaTeX_Main-Regular-ypZvNtVU.ttf": f27,
  "assets/KaTeX_Math-BoldItalic-B3XSjfu4.ttf": f28,
  "assets/KaTeX_Math-BoldItalic-CZnvNsCZ.woff2": f29,
  "assets/KaTeX_Math-BoldItalic-iY-2wyZ7.woff": f30,
  "assets/KaTeX_Math-Italic-DA0__PXp.woff": f31,
  "assets/KaTeX_Math-Italic-flOr_0UB.ttf": f32,
  "assets/KaTeX_Math-Italic-t53AETM-.woff2": f33,
  "assets/KaTeX_SansSerif-Bold-CFMepnvq.ttf": f34,
  "assets/KaTeX_SansSerif-Bold-D1sUS0GD.woff2": f35,
  "assets/KaTeX_SansSerif-Bold-DbIhKOiC.woff": f36,
  "assets/KaTeX_SansSerif-Italic-C3H0VqGB.woff2": f37,
  "assets/KaTeX_SansSerif-Italic-DN2j7dab.woff": f38,
  "assets/KaTeX_SansSerif-Italic-YYjJ1zSn.ttf": f39,
  "assets/KaTeX_SansSerif-Regular-BNo7hRIc.ttf": f40,
  "assets/KaTeX_SansSerif-Regular-CS6fqUqJ.woff": f41,
  "assets/KaTeX_SansSerif-Regular-DDBCnlJ7.woff2": f42,
  "assets/KaTeX_Script-Regular-C5JkGWo-.ttf": f43,
  "assets/KaTeX_Script-Regular-D3wIWfF6.woff2": f44,
  "assets/KaTeX_Script-Regular-D5yQViql.woff": f45,
  "assets/KaTeX_Size1-Regular-C195tn64.woff": f46,
  "assets/KaTeX_Size1-Regular-Dbsnue_I.ttf": f47,
  "assets/KaTeX_Size1-Regular-mCD8mA8B.woff2": f48,
  "assets/KaTeX_Size2-Regular-B7gKUWhC.ttf": f49,
  "assets/KaTeX_Size2-Regular-Dy4dx90m.woff2": f50,
  "assets/KaTeX_Size2-Regular-oD1tc_U0.woff": f51,
  "assets/KaTeX_Size3-Regular-CTq5MqoE.woff": f52,
  "assets/KaTeX_Size3-Regular-DgpXs0kz.ttf": f53,
  "assets/KaTeX_Size4-Regular-BF-4gkZK.woff": f54,
  "assets/KaTeX_Size4-Regular-DWFBv043.ttf": f55,
  "assets/KaTeX_Size4-Regular-Dl5lxZxV.woff2": f56,
  "assets/KaTeX_Typewriter-Regular-C0xS9mPB.woff": f57,
  "assets/KaTeX_Typewriter-Regular-CO6r4hn1.woff2": f58,
  "assets/KaTeX_Typewriter-Regular-D3Ib7_Hf.ttf": f59,
  "assets/arc-CVzW8rIw.js": f60,
  "assets/arc-CVzW8rIw.js.map": f61,
  "assets/architectureDiagram-3BPJPVTR-B8DxxJjO.js": f62,
  "assets/architectureDiagram-3BPJPVTR-B8DxxJjO.js.map": f63,
  "assets/blockDiagram-GPEHLZMM-Cwi8yMgg.js": f64,
  "assets/blockDiagram-GPEHLZMM-Cwi8yMgg.js.map": f65,
  "assets/c4Diagram-AAUBKEIU-oBCovhPE.js": f66,
  "assets/c4Diagram-AAUBKEIU-oBCovhPE.js.map": f67,
  "assets/channel-_zKLHA6o.js": f68,
  "assets/channel-_zKLHA6o.js.map": f69,
  "assets/chunk-2J33WTMH-Bm2V3Iv1.js": f70,
  "assets/chunk-2J33WTMH-Bm2V3Iv1.js.map": f71,
  "assets/chunk-4BX2VUAB-Cyp1xMGZ.js": f72,
  "assets/chunk-4BX2VUAB-Cyp1xMGZ.js.map": f73,
  "assets/chunk-55IACEB6-Dhe_8U6Q.js": f74,
  "assets/chunk-55IACEB6-Dhe_8U6Q.js.map": f75,
  "assets/chunk-727SXJPM-C3Feq6dm.js": f76,
  "assets/chunk-727SXJPM-C3Feq6dm.js.map": f77,
  "assets/chunk-AQP2D5EJ-DhgwVsdI.js": f78,
  "assets/chunk-AQP2D5EJ-DhgwVsdI.js.map": f79,
  "assets/chunk-FMBD7UC4-e6vAsuuH.js": f80,
  "assets/chunk-FMBD7UC4-e6vAsuuH.js.map": f81,
  "assets/chunk-ND2GUHAM-FwQ3Wrck.js": f82,
  "assets/chunk-ND2GUHAM-FwQ3Wrck.js.map": f83,
  "assets/chunk-QZHKN3VN-DTGpMUZK.js": f84,
  "assets/chunk-QZHKN3VN-DTGpMUZK.js.map": f85,
  "assets/classDiagram-4FO5ZUOK-C1xAtkQI.js": f86,
  "assets/classDiagram-4FO5ZUOK-C1xAtkQI.js.map": f87,
  "assets/classDiagram-v2-Q7XG4LA2-C1xAtkQI.js": f88,
  "assets/classDiagram-v2-Q7XG4LA2-C1xAtkQI.js.map": f89,
  "assets/cose-bilkent-S5V4N54A-Da33WB1y.js": f90,
  "assets/cose-bilkent-S5V4N54A-Da33WB1y.js.map": f91,
  "assets/cytoscape.esm-BHYC38rz.js": f92,
  "assets/cytoscape.esm-BHYC38rz.js.map": f93,
  "assets/dagre-BM42HDAG-DkIrl7LI.js": f94,
  "assets/dagre-BM42HDAG-DkIrl7LI.js.map": f95,
  "assets/defaultLocale-CrowFXzY.js": f96,
  "assets/defaultLocale-CrowFXzY.js.map": f97,
  "assets/diagram-2AECGRRQ-CWoEKL_V.js": f98,
  "assets/diagram-2AECGRRQ-CWoEKL_V.js.map": f99,
  "assets/diagram-5GNKFQAL-C9Z9Bwq0.js": f100,
  "assets/diagram-5GNKFQAL-C9Z9Bwq0.js.map": f101,
  "assets/diagram-KO2AKTUF-Du2EWJ5m.js": f102,
  "assets/diagram-KO2AKTUF-Du2EWJ5m.js.map": f103,
  "assets/diagram-LMA3HP47-GGH_yPsZ.js": f104,
  "assets/diagram-LMA3HP47-GGH_yPsZ.js.map": f105,
  "assets/diagram-OG6HWLK6-VMYDeT1M.js": f106,
  "assets/diagram-OG6HWLK6-VMYDeT1M.js.map": f107,
  "assets/erDiagram-TEJ5UH35-BEqbMcJY.js": f108,
  "assets/erDiagram-TEJ5UH35-BEqbMcJY.js.map": f109,
  "assets/flowDiagram-I6XJVG4X-x2-Ub5G7.js": f110,
  "assets/flowDiagram-I6XJVG4X-x2-Ub5G7.js.map": f111,
  "assets/ganttDiagram-6RSMTGT7-DUcZWSH4.js": f112,
  "assets/ganttDiagram-6RSMTGT7-DUcZWSH4.js.map": f113,
  "assets/gitGraphDiagram-PVQCEYII-Cqwx4SCt.js": f114,
  "assets/gitGraphDiagram-PVQCEYII-Cqwx4SCt.js.map": f115,
  "assets/graph-Dqkl27Ch.js": f116,
  "assets/graph-Dqkl27Ch.js.map": f117,
  "assets/index-DPRjPCXf.css": f118,
  "assets/index-WRN0oQy4.js": f119,
  "assets/index-WRN0oQy4.js.map": f120,
  "assets/infoDiagram-5YYISTIA-D0qbEhQe.js": f121,
  "assets/infoDiagram-5YYISTIA-D0qbEhQe.js.map": f122,
  "assets/init-Gi6I4Gst.js": f123,
  "assets/init-Gi6I4Gst.js.map": f124,
  "assets/ishikawaDiagram-YF4QCWOH-DbHmi4h_.js": f125,
  "assets/ishikawaDiagram-YF4QCWOH-DbHmi4h_.js.map": f126,
  "assets/journeyDiagram-JHISSGLW-Dr1IoxSi.js": f127,
  "assets/journeyDiagram-JHISSGLW-Dr1IoxSi.js.map": f128,
  "assets/kanban-definition-UN3LZRKU--k1I1t4r.js": f129,
  "assets/kanban-definition-UN3LZRKU--k1I1t4r.js.map": f130,
  "assets/layout-DO9UvE1P.js": f131,
  "assets/layout-DO9UvE1P.js.map": f132,
  "assets/linear-DSm5fsPb.js": f133,
  "assets/linear-DSm5fsPb.js.map": f134,
  "assets/mermaid.core-Ap_9pv9R.js": f135,
  "assets/mermaid.core-Ap_9pv9R.js.map": f136,
  "assets/mindmap-definition-RKZ34NQL-BEdV6YPh.js": f137,
  "assets/mindmap-definition-RKZ34NQL-BEdV6YPh.js.map": f138,
  "assets/ordinal-Cboi1Yqb.js": f139,
  "assets/ordinal-Cboi1Yqb.js.map": f140,
  "assets/pieDiagram-4H26LBE5-DEXyv75m.js": f141,
  "assets/pieDiagram-4H26LBE5-DEXyv75m.js.map": f142,
  "assets/quadrantDiagram-W4KKPZXB-D_kYuYHy.js": f143,
  "assets/quadrantDiagram-W4KKPZXB-D_kYuYHy.js.map": f144,
  "assets/requirementDiagram-4Y6WPE33-BKzZtHsA.js": f145,
  "assets/requirementDiagram-4Y6WPE33-BKzZtHsA.js.map": f146,
  "assets/sankeyDiagram-5OEKKPKP-BgQMyrSg.js": f147,
  "assets/sankeyDiagram-5OEKKPKP-BgQMyrSg.js.map": f148,
  "assets/sequenceDiagram-3UESZ5HK-GtB0e6xu.js": f149,
  "assets/sequenceDiagram-3UESZ5HK-GtB0e6xu.js.map": f150,
  "assets/stateDiagram-AJRCARHV-BFVUMSdO.js": f151,
  "assets/stateDiagram-AJRCARHV-BFVUMSdO.js.map": f152,
  "assets/stateDiagram-v2-BHNVJYJU-xfmCgDp0.js": f153,
  "assets/stateDiagram-v2-BHNVJYJU-xfmCgDp0.js.map": f154,
  "assets/timeline-definition-PNZ67QCA-D8AY6Ugr.js": f155,
  "assets/timeline-definition-PNZ67QCA-D8AY6Ugr.js.map": f156,
  "assets/vennDiagram-CIIHVFJN--GtxLeUW.js": f157,
  "assets/vennDiagram-CIIHVFJN--GtxLeUW.js.map": f158,
  "assets/wardley-L42UT6IY-DkC-hCz1.js": f159,
  "assets/wardley-L42UT6IY-DkC-hCz1.js.map": f160,
  "assets/wardleyDiagram-YWT4CUSO-CW3AQD05.js": f161,
  "assets/wardleyDiagram-YWT4CUSO-CW3AQD05.js.map": f162,
  "assets/xychartDiagram-2RQKCTM6-BNQB4-xZ.js": f163,
  "assets/xychartDiagram-2RQKCTM6-BNQB4-xZ.js.map": f164,
  "brainmdlogo.png": f165,
  "icon.svg": f166,
  "icon_.svg": f167,
  "index.html": f168,
  "logo.svg": f169,
  "manifest.webmanifest": f170,
  "sw.js": f171,
};

export const ASSETS_GENERATED_AT: number | null = 1779986456239;
